export const ACTION_GET_CURRENT_USER = 'ACTION_GET_CURRENT_USER';
export const ACTION_LOGIN  = 'ACTION_LOGIN';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CAN_ACCESS_DASHBOARD = 'SET_CAN_ACCESS_DASHBOARD';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CAN_ACCESS_DASHBOARD = 'GET_CAN_ACCESS_DASHBOARD';
