export const ACTION_GET_CURRENT_USER = 'ACTION_GET_CURRENT_USER';
export const ACTION_LOGIN  = 'ACTION_LOGIN';
export const ACTION_GET_ENVIRONMENT_USERS = 'ACTION_GET_ENVIRONMENT_USERS';
export const ACTION_RESET_REGISTRATION_HASH = 'ACTION_RESET_REGISTRATION_HASH';
export const ACTION_GET_REGISTRATION_HASH = 'ACTION_GET_REGISTRATION_HASH';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CAN_ACCESS_DASHBOARD = 'SET_CAN_ACCESS_DASHBOARD';
export const SET_ENVIRONMENT_USERS = 'SET_ENVIRONMENT_USERS';
export const SET_REGISTRATION_HASH = 'SET_REGISTRATION_HASH';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CAN_ACCESS_DASHBOARD = 'GET_CAN_ACCESS_DASHBOARD';
export const GET_ENVIRONMENT_USERS = 'GET_ENVIRONMENT_USERS';
export const GET_REGISTRATION_HASH = 'GET_REGISTRATION_HASH';
