export const ACTION_GET_APPLIABLE_ADVERTISEMENTS = 'ACTION_GET_APPLIABLE_ADVERTISEMENTS';

export const GET_APPLIABLE_ADVERTISEMENTS = 'GET_APPLIABLE_ADVERTISEMENTS';

export const SET_APPLIABLE_ADVERTISEMENTS = 'SET_APPLIABLE_ADVERTISEMENTS';
