export const ACTION_GET_ADVERTISEMENTS = 'ACTION_GET_ADVERTISEMENTS';
export const ACTION_GET_CATEGORIES = 'ACTION_GET_CATEGORIES';
export const ACTION_GET_CURRENT_ADVERTISEMENT = 'ACTION_GET_CURRENT_ADVERTISEMENT';

export const GET_ADVERTISEMENTS = 'GET_ADVERTISEMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CURRENT_ADVERTISEMENT = 'GET_CURRENT_ADVERTISEMENT';

export const SET_ADVERTISEMENTS = 'SET_ADVERTISEMENTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_ADVERTISEMENT = 'SET_CURRENT_ADVERTISEMENT';
