// Actions
export const ACTION_GET_ADVERTISEMENTS = 'ACTION_GET_ADVERTISEMENTS';
export const ACTION_GET_CATEGORIES = 'ACTION_GET_CATEGORIES';
export const ACTION_GET_CURRENT_ADVERTISEMENT = 'ACTION_GET_CURRENT_ADVERTISEMENT';
export const ACTION_INCREASE_LIMIT = 'ACTION_INCREASE_LIMIT';


//Getters
export const GET_ADVERTISEMENTS = 'GET_ADVERTISEMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CURRENT_ADVERTISEMENT = 'GET_CURRENT_ADVERTISEMENT';
export const GET_CURRENT_SEARCH_ITEM = 'GET_CURRENT_SEARCH_ITEM';
export const GET_IS_BOTTOM_REACHED = 'GET_IS_BOTTOM_REACHED';


//Mutations
export const SET_ADVERTISEMENTS = 'SET_ADVERTISEMENTS';
export const ADD_ADVERTISEMENTS = 'ADD_ADVERTISEMENTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_ADVERTISEMENT = 'SET_CURRENT_ADVERTISEMENT';
export const SET_IS_BOTTOM_REACHED = 'SET_IS_BOTTOM_REACHED';

//Search
export const SET_SEARCH_TITLE = 'SET_SEARCH_TITLE';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const SET_SEARCH_LOCATION = 'SET_SEARCH_LOCATION';
export const SET_SEARCH_LIMIT = 'SET_SEARCH_LIMIT';
export const SET_SEARCH_OFFSET = 'SET_SEARCH_OFFSET';
