// Actions
export const ACTION_GET_ENVIRONMENT_ADVERTISEMENTS = 'ACTION_GET_ENVIRONMENT_ADVERTISEMENTS';
export const ACTION_SAVE_ADVERTISEMENT = 'ACTION_SAVE_ADVERTISEMENT';

// Getters
export const GET_ENVIRONMENT_ADVERTISEMENTS = 'GET_ENVIRONMENT_ADVERTISEMENTS';
export const GET_SHOW_MODAL = 'GET_SHOW_MODAL';

// Mutations
export const SET_ENVIRONMENT_ADVERTISEMENTS = 'SET_ENVIRONMENT_ADVERTISEMENTS';
export const TOGGLE_CREATE_ADVERTISEMENT_MODAL = 'TOGGLE_CREATE_ADVERTISEMENT_MODAL';
