export const ACTION_GET_ENVIRONMENT_ADVERTISEMENTS = 'ACTION_GET_ENVIRONMENT_ADVERTISEMENTS';

export const GET_ENVIRONMENT_ADVERTISEMENTS = 'GET_ENVIRONMENT_ADVERTISEMENTS';

export const SET_ENVIRONMENT_ADVERTISEMENTS = 'SET_ENVIRONMENT_ADVERTISEMENTS';
